[package]
name = "rusty-raytracer"
version = "0.1.0"
authors = ["lemonteaa <lemontea.Tom@gmail.com>"]

[dependencies]
image = "0.20.0"
nalgebra = "0.16.0"
nalgebra-glm = "0.1"
alga = "0.7.2"
rand = "0.5.5"
